### ISSUE TITLE
Ui Needs a redesign

### ISSUE THREAD

**Issue by Jarmahent** [Jarmahent/Clippy#5]
It looks outdated and ugly

**Comment by Crowes** [comment]
Screenshot of it atm?

**Comment by Jarmahent** [comment]
@Crowes [Windows 10](https://i.imgur.com/VJydM7S.png)

**Comment by Jarmahent** [comment]
Something along the lines of [Photo](http://photonkit.com/) would be nice. It doesnt have to be specifically Photon but something that looks like it!

**Comment by Jarmahent** [comment]
redesigned the Settings page, 1 down 2 more to go:

![alt text](https://i.imgur.com/xyMXVJ9.png "Logo Title Text 1")

**Comment by Jarmahent** [comment]
This issue will be only for the setting page and that was already designed  so im closing it and opening 2 new issues.
